package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/ExcecaoVisitaASAHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

abstract public class ExcecaoVisitaASAHelper
{
  private static String  _id = "IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0";

  public static void insert (org.omg.CORBA.Any a, br.univali.portugol.integracao.asa.ExcecaoVisitaASA that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.univali.portugol.integracao.asa.ExcecaoVisitaASA extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "mensagem",
            _tcOf_members0,
            null);
          _tcOf_members0 = br.univali.portugol.integracao.asa.NoHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "no",
            _tcOf_members0,
            null);
          _tcOf_members0 = br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "arvoreSintaticaAbstrata",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.id (), "ExcecaoVisitaASA", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.univali.portugol.integracao.asa.ExcecaoVisitaASA read (org.omg.CORBA.portable.InputStream istream)
  {
    br.univali.portugol.integracao.asa.ExcecaoVisitaASA value = new br.univali.portugol.integracao.asa.ExcecaoVisitaASA ();
    // read and discard the repository ID
    istream.read_string ();
    value.mensagem = istream.read_string ();
    value.no = br.univali.portugol.integracao.asa.NoHelper.read (istream);
    value.arvoreSintaticaAbstrata = br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.univali.portugol.integracao.asa.ExcecaoVisitaASA value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_string (value.mensagem);
    br.univali.portugol.integracao.asa.NoHelper.write (ostream, value.no);
    br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataHelper.write (ostream, value.arvoreSintaticaAbstrata);
  }

}
