package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/ListaNoBlocoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

abstract public class ListaNoBlocoHelper
{
  private static String  _id = "IDL:br/univali/portugol/integracao/asa/ListaNoBloco:1.0";

  public static void insert (org.omg.CORBA.Any a, br.univali.portugol.integracao.asa.NoBloco[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.univali.portugol.integracao.asa.NoBloco[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = br.univali.portugol.integracao.asa.NoBlocoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (br.univali.portugol.integracao.asa.ListaNoBlocoHelper.id (), "ListaNoBloco", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.univali.portugol.integracao.asa.NoBloco[] read (org.omg.CORBA.portable.InputStream istream)
  {
    br.univali.portugol.integracao.asa.NoBloco value[] = null;
    int _len0 = istream.read_long ();
    value = new br.univali.portugol.integracao.asa.NoBloco[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = br.univali.portugol.integracao.asa.NoBlocoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.univali.portugol.integracao.asa.NoBloco[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      br.univali.portugol.integracao.asa.NoBlocoHelper.write (ostream, value[_i0]);
  }

}
