package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/ModoAcesso.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public class ModoAcesso implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static br.univali.portugol.integracao.asa.ModoAcesso[] __array = new br.univali.portugol.integracao.asa.ModoAcesso [__size];

  public static final int _POR_VALOR = 0;
  public static final br.univali.portugol.integracao.asa.ModoAcesso POR_VALOR = new br.univali.portugol.integracao.asa.ModoAcesso(_POR_VALOR);
  public static final int _POR_REFERENCIA = 1;
  public static final br.univali.portugol.integracao.asa.ModoAcesso POR_REFERENCIA = new br.univali.portugol.integracao.asa.ModoAcesso(_POR_REFERENCIA);

  public int value ()
  {
    return __value;
  }

  public static br.univali.portugol.integracao.asa.ModoAcesso from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ModoAcesso (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ModoAcesso
