package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/NoDeclaracaoParametroPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public abstract class NoDeclaracaoParametroPOA extends org.omg.PortableServer.Servant
 implements br.univali.portugol.integracao.asa.NoDeclaracaoParametroOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getIndice", new java.lang.Integer (0));
    _methods.put ("getNome", new java.lang.Integer (1));
    _methods.put ("getTipoDado", new java.lang.Integer (2));
    _methods.put ("getQuantificador", new java.lang.Integer (3));
    _methods.put ("getModoAcesso", new java.lang.Integer (4));
    _methods.put ("getTrechoCodigoFonteNome", new java.lang.Integer (5));
    _methods.put ("getTrechoCodigoFonteTipoDado", new java.lang.Integer (6));
    _methods.put ("aceitar", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/univali/portugol/integracao/asa/NoDeclaracaoParametro/getIndice
       {
         int $result = (int)0;
         $result = this.getIndice ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // br/univali/portugol/integracao/asa/NoDeclaracaoParametro/getNome
       {
         String $result = null;
         $result = this.getNome ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // br/univali/portugol/integracao/asa/NoDeclaracaoParametro/getTipoDado
       {
         br.univali.portugol.integracao.asa.TipoDado $result = null;
         $result = this.getTipoDado ();
         out = $rh.createReply();
         br.univali.portugol.integracao.asa.TipoDadoHelper.write (out, $result);
         break;
       }

       case 3:  // br/univali/portugol/integracao/asa/NoDeclaracaoParametro/getQuantificador
       {
         br.univali.portugol.integracao.asa.Quantificador $result = null;
         $result = this.getQuantificador ();
         out = $rh.createReply();
         br.univali.portugol.integracao.asa.QuantificadorHelper.write (out, $result);
         break;
       }

       case 4:  // br/univali/portugol/integracao/asa/NoDeclaracaoParametro/getModoAcesso
       {
         br.univali.portugol.integracao.asa.ModoAcesso $result = null;
         $result = this.getModoAcesso ();
         out = $rh.createReply();
         br.univali.portugol.integracao.asa.ModoAcessoHelper.write (out, $result);
         break;
       }

       case 5:  // br/univali/portugol/integracao/asa/NoDeclaracaoParametro/getTrechoCodigoFonteNome
       {
         br.univali.portugol.integracao.asa.TrechoCodigoFonte $result = null;
         $result = this.getTrechoCodigoFonteNome ();
         out = $rh.createReply();
         br.univali.portugol.integracao.asa.TrechoCodigoFonteHelper.write (out, $result);
         break;
       }

       case 6:  // br/univali/portugol/integracao/asa/NoDeclaracaoParametro/getTrechoCodigoFonteTipoDado
       {
         br.univali.portugol.integracao.asa.TrechoCodigoFonte $result = null;
         $result = this.getTrechoCodigoFonteTipoDado ();
         out = $rh.createReply();
         br.univali.portugol.integracao.asa.TrechoCodigoFonteHelper.write (out, $result);
         break;
       }

       case 7:  // br/univali/portugol/integracao/asa/No/aceitar
       {
         try {
           br.univali.portugol.integracao.asa.VisitanteASA visitante = br.univali.portugol.integracao.asa.VisitanteASAHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.aceitar (visitante);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/asa/NoDeclaracaoParametro:1.0", 
    "IDL:br/univali/portugol/integracao/asa/No:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public NoDeclaracaoParametro _this() 
  {
    return NoDeclaracaoParametroHelper.narrow(
    super._this_object());
  }

  public NoDeclaracaoParametro _this(org.omg.CORBA.ORB orb) 
  {
    return NoDeclaracaoParametroHelper.narrow(
    super._this_object(orb));
  }


} // class NoDeclaracaoParametroPOA
