package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/NoDeclaracaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface NoDeclaracaoOperations  extends br.univali.portugol.integracao.asa.NoBlocoOperations
{
  String getNome ();
  boolean constante ();
  br.univali.portugol.integracao.asa.TipoDado getTipoDado ();
  br.univali.portugol.integracao.asa.NoExpressao getInicializacao ();
  br.univali.portugol.integracao.asa.TrechoCodigoFonte getTrechoCodigoFonteNome ();
  br.univali.portugol.integracao.asa.TrechoCodigoFonte getTrechoCodigoFonteTipoDado ();
} // interface NoDeclaracaoOperations
