package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/OperacaoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

abstract public class OperacaoHelper
{
  private static String  _id = "IDL:br/univali/portugol/integracao/asa/Operacao:1.0";

  public static void insert (org.omg.CORBA.Any a, br.univali.portugol.integracao.asa.Operacao that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.univali.portugol.integracao.asa.Operacao extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (br.univali.portugol.integracao.asa.OperacaoHelper.id (), "Operacao", new String[] { "IGUALDADE", "DIFERENCA", "ATRIBUICAO", "E", "OU", "MAIOR", "MAIOR_IGUAL", "MENOR", "MENOR_IGUAL", "SOMA", "SOMA_ACUMULATIVA", "SUBTRACAO", "SUBTRACAO_ACUMULATIVA", "DIVISAO", "DIVISAO_ACUMULATIVA", "MULTIPLICACAO", "MULTIPLICACAO_ACUMULATIVA", "MODULO", "MODULO_ACUMULATIVO", "OPERACAO_INVALIDA"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.univali.portugol.integracao.asa.Operacao read (org.omg.CORBA.portable.InputStream istream)
  {
    return br.univali.portugol.integracao.asa.Operacao.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.univali.portugol.integracao.asa.Operacao value)
  {
    ostream.write_long (value.value ());
  }

}
