package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/Quantificador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public class Quantificador implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static br.univali.portugol.integracao.asa.Quantificador[] __array = new br.univali.portugol.integracao.asa.Quantificador [__size];

  public static final int _VALOR = 0;
  public static final br.univali.portugol.integracao.asa.Quantificador VALOR = new br.univali.portugol.integracao.asa.Quantificador(_VALOR);
  public static final int _VETOR = 1;
  public static final br.univali.portugol.integracao.asa.Quantificador VETOR = new br.univali.portugol.integracao.asa.Quantificador(_VETOR);
  public static final int _MATRIZ = 2;
  public static final br.univali.portugol.integracao.asa.Quantificador MATRIZ = new br.univali.portugol.integracao.asa.Quantificador(_MATRIZ);

  public int value ()
  {
    return __value;
  }

  public static br.univali.portugol.integracao.asa.Quantificador from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Quantificador (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Quantificador
