package br.univali.portugol.integracao;


/**
* br/univali/portugol/integracao/_ProgramaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public class _ProgramaStub extends org.omg.CORBA.portable.ObjectImpl implements br.univali.portugol.integracao.Programa
{

  public void adicionarObservadorExecucao (br.univali.portugol.integracao.execucao.ObservadorExecucao observador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("adicionarObservadorExecucao", true);
                br.univali.portugol.integracao.execucao.ObservadorExecucaoHelper.write ($out, observador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                adicionarObservadorExecucao (observador        );
            } finally {
                _releaseReply ($in);
            }
  } // adicionarObservadorExecucao

  public void removerObservadorExecucao (br.univali.portugol.integracao.execucao.ObservadorExecucao observador)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removerObservadorExecucao", true);
                br.univali.portugol.integracao.execucao.ObservadorExecucaoHelper.write ($out, observador);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removerObservadorExecucao (observador        );
            } finally {
                _releaseReply ($in);
            }
  } // removerObservadorExecucao

  public void executar (String[] parametros)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("executar", true);
                br.univali.portugol.integracao.ParametrosHelper.write ($out, parametros);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                executar (parametros        );
            } finally {
                _releaseReply ($in);
            }
  } // executar


  //void depurar() throws Exception;
  public void interromper ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("interromper", true);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                interromper (        );
            } finally {
                _releaseReply ($in);
            }
  } // interromper

  public br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataPrograma getArvoreSintaticaAbstrata ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getArvoreSintaticaAbstrata", true);
                $in = _invoke ($out);
                br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataPrograma $result = br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataProgramaHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getArvoreSintaticaAbstrata (        );
            } finally {
                _releaseReply ($in);
            }
  } // getArvoreSintaticaAbstrata

  public void setFuncaoInicial (String funcaoInicial)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setFuncaoInicial", true);
                $out.write_string (funcaoInicial);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setFuncaoInicial (funcaoInicial        );
            } finally {
                _releaseReply ($in);
            }
  } // setFuncaoInicial

  public String getFuncaoInicial ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getFuncaoInicial", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getFuncaoInicial (        );
            } finally {
                _releaseReply ($in);
            }
  } // getFuncaoInicial

  public void setEntrada (br.univali.portugol.integracao.execucao.Entrada entrada)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setEntrada", true);
                br.univali.portugol.integracao.execucao.EntradaHelper.write ($out, entrada);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setEntrada (entrada        );
            } finally {
                _releaseReply ($in);
            }
  } // setEntrada

  public void setSaida (br.univali.portugol.integracao.execucao.Saida saida)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setSaida", true);
                br.univali.portugol.integracao.execucao.SaidaHelper.write ($out, saida);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setSaida (saida        );
            } finally {
                _releaseReply ($in);
            }
  } // setSaida

  public String getCodigo ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCodigo", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCodigo (        );
            } finally {
                _releaseReply ($in);
            }
  } // getCodigo

  public boolean isExecutando ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("isExecutando", true);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return isExecutando (        );
            } finally {
                _releaseReply ($in);
            }
  } // isExecutando

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/Programa:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ProgramaStub
