package br.univali.portugol.integracao;


/**
* br/univali/portugol/integracao/ErroCompilacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public final class ErroCompilacao extends org.omg.CORBA.UserException
{
  public br.univali.portugol.integracao.analise.ResultadoAnalise resultadoAnalise = null;

  public ErroCompilacao ()
  {
    super(ErroCompilacaoHelper.id());
  } // ctor

  public ErroCompilacao (br.univali.portugol.integracao.analise.ResultadoAnalise _resultadoAnalise)
  {
    super(ErroCompilacaoHelper.id());
    resultadoAnalise = _resultadoAnalise;
  } // ctor


  public ErroCompilacao (String $reason, br.univali.portugol.integracao.analise.ResultadoAnalise _resultadoAnalise)
  {
    super(ErroCompilacaoHelper.id() + "  " + $reason);
    resultadoAnalise = _resultadoAnalise;
  } // ctor

} // class ErroCompilacao
