package br.univali.portugol.integracao;


/**
* br/univali/portugol/integracao/PortugolPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public abstract class PortugolPOA extends org.omg.PortableServer.Servant
 implements br.univali.portugol.integracao.PortugolOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("analisar", new java.lang.Integer (0));
    _methods.put ("compilar", new java.lang.Integer (1));
    _methods.put ("encerrar", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/univali/portugol/integracao/Portugol/analisar
       {
         String codigo = in.read_string ();
         br.univali.portugol.integracao.analise.ResultadoAnalise $result = null;
         $result = this.analisar (codigo);
         out = $rh.createReply();
         br.univali.portugol.integracao.analise.ResultadoAnaliseHelper.write (out, $result);
         break;
       }

       case 1:  // br/univali/portugol/integracao/Portugol/compilar
       {
         try {
           String codigo = in.read_string ();
           br.univali.portugol.integracao.Programa $result = null;
           $result = this.compilar (codigo);
           out = $rh.createReply();
           br.univali.portugol.integracao.ProgramaHelper.write (out, $result);
         } catch (br.univali.portugol.integracao.ErroCompilacao $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.ErroCompilacaoHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // br/univali/portugol/integracao/Portugol/encerrar
       {
         this.encerrar ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/Portugol:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Portugol _this() 
  {
    return PortugolHelper.narrow(
    super._this_object());
  }

  public Portugol _this(org.omg.CORBA.ORB orb) 
  {
    return PortugolHelper.narrow(
    super._this_object(orb));
  }


} // class PortugolPOA
