package br.univali.portugol.integracao;


/**
* br/univali/portugol/integracao/ProgramaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface ProgramaOperations 
{
  void adicionarObservadorExecucao (br.univali.portugol.integracao.execucao.ObservadorExecucao observador);
  void removerObservadorExecucao (br.univali.portugol.integracao.execucao.ObservadorExecucao observador);
  void executar (String[] parametros);

  //void depurar() throws Exception;
  void interromper ();
  br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataPrograma getArvoreSintaticaAbstrata ();
  void setFuncaoInicial (String funcaoInicial);
  String getFuncaoInicial ();
  void setEntrada (br.univali.portugol.integracao.execucao.Entrada entrada);
  void setSaida (br.univali.portugol.integracao.execucao.Saida saida);
  String getCodigo ();
  boolean isExecutando ();
} // interface ProgramaOperations
