package br.univali.portugol.integracao;


/**
* br/univali/portugol/integracao/ProgramaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public abstract class ProgramaPOA extends org.omg.PortableServer.Servant
 implements br.univali.portugol.integracao.ProgramaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("adicionarObservadorExecucao", new java.lang.Integer (0));
    _methods.put ("removerObservadorExecucao", new java.lang.Integer (1));
    _methods.put ("executar", new java.lang.Integer (2));
    _methods.put ("interromper", new java.lang.Integer (3));
    _methods.put ("getArvoreSintaticaAbstrata", new java.lang.Integer (4));
    _methods.put ("setFuncaoInicial", new java.lang.Integer (5));
    _methods.put ("getFuncaoInicial", new java.lang.Integer (6));
    _methods.put ("setEntrada", new java.lang.Integer (7));
    _methods.put ("setSaida", new java.lang.Integer (8));
    _methods.put ("getCodigo", new java.lang.Integer (9));
    _methods.put ("isExecutando", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/univali/portugol/integracao/Programa/adicionarObservadorExecucao
       {
         br.univali.portugol.integracao.execucao.ObservadorExecucao observador = br.univali.portugol.integracao.execucao.ObservadorExecucaoHelper.read (in);
         this.adicionarObservadorExecucao (observador);
         out = $rh.createReply();
         break;
       }

       case 1:  // br/univali/portugol/integracao/Programa/removerObservadorExecucao
       {
         br.univali.portugol.integracao.execucao.ObservadorExecucao observador = br.univali.portugol.integracao.execucao.ObservadorExecucaoHelper.read (in);
         this.removerObservadorExecucao (observador);
         out = $rh.createReply();
         break;
       }

       case 2:  // br/univali/portugol/integracao/Programa/executar
       {
         String parametros[] = br.univali.portugol.integracao.ParametrosHelper.read (in);
         this.executar (parametros);
         out = $rh.createReply();
         break;
       }


  //void depurar() throws Exception;
       case 3:  // br/univali/portugol/integracao/Programa/interromper
       {
         this.interromper ();
         out = $rh.createReply();
         break;
       }

       case 4:  // br/univali/portugol/integracao/Programa/getArvoreSintaticaAbstrata
       {
         br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataPrograma $result = null;
         $result = this.getArvoreSintaticaAbstrata ();
         out = $rh.createReply();
         br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataProgramaHelper.write (out, $result);
         break;
       }

       case 5:  // br/univali/portugol/integracao/Programa/setFuncaoInicial
       {
         String funcaoInicial = in.read_string ();
         this.setFuncaoInicial (funcaoInicial);
         out = $rh.createReply();
         break;
       }

       case 6:  // br/univali/portugol/integracao/Programa/getFuncaoInicial
       {
         String $result = null;
         $result = this.getFuncaoInicial ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // br/univali/portugol/integracao/Programa/setEntrada
       {
         br.univali.portugol.integracao.execucao.Entrada entrada = br.univali.portugol.integracao.execucao.EntradaHelper.read (in);
         this.setEntrada (entrada);
         out = $rh.createReply();
         break;
       }

       case 8:  // br/univali/portugol/integracao/Programa/setSaida
       {
         br.univali.portugol.integracao.execucao.Saida saida = br.univali.portugol.integracao.execucao.SaidaHelper.read (in);
         this.setSaida (saida);
         out = $rh.createReply();
         break;
       }

       case 9:  // br/univali/portugol/integracao/Programa/getCodigo
       {
         String $result = null;
         $result = this.getCodigo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // br/univali/portugol/integracao/Programa/isExecutando
       {
         boolean $result = false;
         $result = this.isExecutando ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/Programa:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Programa _this() 
  {
    return ProgramaHelper.narrow(
    super._this_object());
  }

  public Programa _this(org.omg.CORBA.ORB orb) 
  {
    return ProgramaHelper.narrow(
    super._this_object(orb));
  }


} // class ProgramaPOA
