package br.univali.portugol.integracao;


/**
* br/univali/portugol/integracao/Excecao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public final class Excecao extends org.omg.CORBA.UserException
{
  public String mensagem = null;

  public Excecao ()
  {
    super(ExcecaoHelper.id());
  } // ctor

  public Excecao (String _mensagem)
  {
    super(ExcecaoHelper.id());
    mensagem = _mensagem;
  } // ctor


  public Excecao (String $reason, String _mensagem)
  {
    super(ExcecaoHelper.id() + "  " + $reason);
    mensagem = _mensagem;
  } // ctor

} // class Excecao
