package br.univali.portugol.integracao;


/**
* br/univali/portugol/integracao/PortugolOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface PortugolOperations 
{
  br.univali.portugol.integracao.analise.ResultadoAnalise analisar (String codigo);
  br.univali.portugol.integracao.Programa compilar (String codigo) throws br.univali.portugol.integracao.ErroCompilacao;
  void encerrar ();
} // interface PortugolOperations
