package br.univali.portugol.integracao.execucao;


/**
* br/univali/portugol/integracao/execucao/EntradaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface EntradaOperations 
{
  org.omg.CORBA.Any ler (br.univali.portugol.integracao.asa.TipoDado tipoDado) throws br.univali.portugol.integracao.Excecao;
} // interface EntradaOperations
