package br.univali.portugol.integracao.execucao;


/**
* br/univali/portugol/integracao/execucao/EntradaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public abstract class EntradaPOA extends org.omg.PortableServer.Servant
 implements br.univali.portugol.integracao.execucao.EntradaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ler", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/univali/portugol/integracao/execucao/Entrada/ler
       {
         try {
           br.univali.portugol.integracao.asa.TipoDado tipoDado = br.univali.portugol.integracao.asa.TipoDadoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.ler (tipoDado);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.Excecao $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.ExcecaoHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/execucao/Entrada:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Entrada _this() 
  {
    return EntradaHelper.narrow(
    super._this_object());
  }

  public Entrada _this(org.omg.CORBA.ORB orb) 
  {
    return EntradaHelper.narrow(
    super._this_object(orb));
  }


} // class EntradaPOA
