package br.univali.portugol.integracao.execucao;


/**
* br/univali/portugol/integracao/execucao/ModoEncerramentoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
abstract public class ModoEncerramentoHelper
{
  private static String  _id = "IDL:br/univali/portugol/integracao/execucao/ModoEncerramento:1.0";

  public static void insert (org.omg.CORBA.Any a, br.univali.portugol.integracao.execucao.ModoEncerramento that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.univali.portugol.integracao.execucao.ModoEncerramento extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (br.univali.portugol.integracao.execucao.ModoEncerramentoHelper.id (), "ModoEncerramento", new String[] { "NORMAL", "ERRO", "INTERRUPCAO"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.univali.portugol.integracao.execucao.ModoEncerramento read (org.omg.CORBA.portable.InputStream istream)
  {
    return br.univali.portugol.integracao.execucao.ModoEncerramento.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.univali.portugol.integracao.execucao.ModoEncerramento value)
  {
    ostream.write_long (value.value ());
  }

}
