package br.univali.portugol.integracao.execucao;


/**
* br/univali/portugol/integracao/execucao/ObservadorExecucaoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public abstract class ObservadorExecucaoPOA extends org.omg.PortableServer.Servant
 implements br.univali.portugol.integracao.execucao.ObservadorExecucaoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("execucaoIniciada", new java.lang.Integer (0));
    _methods.put ("execucaoEncerrada", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/univali/portugol/integracao/execucao/ObservadorExecucao/execucaoIniciada
       {
         br.univali.portugol.integracao.Programa programa = br.univali.portugol.integracao.ProgramaHelper.read (in);
         this.execucaoIniciada (programa);
         out = $rh.createReply();
         break;
       }

       case 1:  // br/univali/portugol/integracao/execucao/ObservadorExecucao/execucaoEncerrada
       {
         br.univali.portugol.integracao.Programa programa = br.univali.portugol.integracao.ProgramaHelper.read (in);
         br.univali.portugol.integracao.execucao.ResultadoExecucao resultadoExecucao = br.univali.portugol.integracao.execucao.ResultadoExecucaoHelper.read (in);
         this.execucaoEncerrada (programa, resultadoExecucao);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/execucao/ObservadorExecucao:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ObservadorExecucao _this() 
  {
    return ObservadorExecucaoHelper.narrow(
    super._this_object());
  }

  public ObservadorExecucao _this(org.omg.CORBA.ORB orb) 
  {
    return ObservadorExecucaoHelper.narrow(
    super._this_object(orb));
  }


} // class ObservadorExecucaoPOA
