package br.univali.portugol.integracao.execucao;


/**
* br/univali/portugol/integracao/execucao/ObservadorExecucaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface ObservadorExecucaoOperations 
{
  void execucaoIniciada (br.univali.portugol.integracao.Programa programa);
  void execucaoEncerrada (br.univali.portugol.integracao.Programa programa, br.univali.portugol.integracao.execucao.ResultadoExecucao resultadoExecucao);
} // interface ObservadorExecucaoOperations
