package br.univali.portugol.integracao.execucao;


/**
* br/univali/portugol/integracao/execucao/ResultadoExecucaoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public abstract class ResultadoExecucaoPOA extends org.omg.PortableServer.Servant
 implements br.univali.portugol.integracao.execucao.ResultadoExecucaoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getTempoExecucao", new java.lang.Integer (0));
    _methods.put ("getModoEncerramento", new java.lang.Integer (1));
    _methods.put ("getErro", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/univali/portugol/integracao/execucao/ResultadoExecucao/getTempoExecucao
       {
         long $result = (long)0;
         $result = this.getTempoExecucao ();
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 1:  // br/univali/portugol/integracao/execucao/ResultadoExecucao/getModoEncerramento
       {
         br.univali.portugol.integracao.execucao.ModoEncerramento $result = null;
         $result = this.getModoEncerramento ();
         out = $rh.createReply();
         br.univali.portugol.integracao.execucao.ModoEncerramentoHelper.write (out, $result);
         break;
       }

       case 2:  // br/univali/portugol/integracao/execucao/ResultadoExecucao/getErro
       {
         br.univali.portugol.integracao.mensagens.ErroExecucao $result = null;
         $result = this.getErro ();
         out = $rh.createReply();
         br.univali.portugol.integracao.mensagens.ErroExecucaoHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/execucao/ResultadoExecucao:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ResultadoExecucao _this() 
  {
    return ResultadoExecucaoHelper.narrow(
    super._this_object());
  }

  public ResultadoExecucao _this(org.omg.CORBA.ORB orb) 
  {
    return ResultadoExecucaoHelper.narrow(
    super._this_object(orb));
  }


} // class ResultadoExecucaoPOA
