package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/_NoDeclaracaoFuncaoStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public class _NoDeclaracaoFuncaoStub extends org.omg.CORBA.portable.ObjectImpl implements br.univali.portugol.integracao.asa.NoDeclaracaoFuncao
{

  public br.univali.portugol.integracao.asa.Quantificador getQuantificador ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getQuantificador", true);
                $in = _invoke ($out);
                br.univali.portugol.integracao.asa.Quantificador $result = br.univali.portugol.integracao.asa.QuantificadorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getQuantificador (        );
            } finally {
                _releaseReply ($in);
            }
  } // getQuantificador

  public br.univali.portugol.integracao.asa.NoBloco[] getBlocos ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getBlocos", true);
                $in = _invoke ($out);
                br.univali.portugol.integracao.asa.NoBloco $result[] = br.univali.portugol.integracao.asa.ListaNoBlocoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getBlocos (        );
            } finally {
                _releaseReply ($in);
            }
  } // getBlocos

  public br.univali.portugol.integracao.asa.NoDeclaracaoParametro[] getParametros ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getParametros", true);
                $in = _invoke ($out);
                br.univali.portugol.integracao.asa.NoDeclaracaoParametro $result[] = br.univali.portugol.integracao.asa.ListaNoDeclaracaoParametroHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getParametros (        );
            } finally {
                _releaseReply ($in);
            }
  } // getParametros

  public String getNome ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNome", true);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getNome (        );
            } finally {
                _releaseReply ($in);
            }
  } // getNome

  public boolean constante ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("constante", true);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return constante (        );
            } finally {
                _releaseReply ($in);
            }
  } // constante

  public br.univali.portugol.integracao.asa.TipoDado getTipoDado ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTipoDado", true);
                $in = _invoke ($out);
                br.univali.portugol.integracao.asa.TipoDado $result = br.univali.portugol.integracao.asa.TipoDadoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTipoDado (        );
            } finally {
                _releaseReply ($in);
            }
  } // getTipoDado

  public br.univali.portugol.integracao.asa.NoExpressao getInicializacao ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getInicializacao", true);
                $in = _invoke ($out);
                br.univali.portugol.integracao.asa.NoExpressao $result = br.univali.portugol.integracao.asa.NoExpressaoHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getInicializacao (        );
            } finally {
                _releaseReply ($in);
            }
  } // getInicializacao

  public br.univali.portugol.integracao.asa.TrechoCodigoFonte getTrechoCodigoFonteNome ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTrechoCodigoFonteNome", true);
                $in = _invoke ($out);
                br.univali.portugol.integracao.asa.TrechoCodigoFonte $result = br.univali.portugol.integracao.asa.TrechoCodigoFonteHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTrechoCodigoFonteNome (        );
            } finally {
                _releaseReply ($in);
            }
  } // getTrechoCodigoFonteNome

  public br.univali.portugol.integracao.asa.TrechoCodigoFonte getTrechoCodigoFonteTipoDado ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getTrechoCodigoFonteTipoDado", true);
                $in = _invoke ($out);
                br.univali.portugol.integracao.asa.TrechoCodigoFonte $result = br.univali.portugol.integracao.asa.TrechoCodigoFonteHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getTrechoCodigoFonteTipoDado (        );
            } finally {
                _releaseReply ($in);
            }
  } // getTrechoCodigoFonteTipoDado

  public org.omg.CORBA.Any aceitar (br.univali.portugol.integracao.asa.VisitanteASA visitante) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("aceitar", true);
                br.univali.portugol.integracao.asa.VisitanteASAHelper.write ($out, visitante);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return aceitar (visitante        );
            } finally {
                _releaseReply ($in);
            }
  } // aceitar

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/asa/NoDeclaracaoFuncao:1.0", 
    "IDL:br/univali/portugol/integracao/asa/NoDeclaracao:1.0", 
    "IDL:br/univali/portugol/integracao/asa/NoBloco:1.0", 
    "IDL:br/univali/portugol/integracao/asa/No:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _NoDeclaracaoFuncaoStub
