package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/_VisitanteASAStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public class _VisitanteASAStub extends org.omg.CORBA.portable.ObjectImpl implements br.univali.portugol.integracao.asa.VisitanteASA
{

  public org.omg.CORBA.Any visitarArvoreSintaticaAbstrataPrograma (br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataPrograma asap) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarArvoreSintaticaAbstrataPrograma", true);
                br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataProgramaHelper.write ($out, asap);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarArvoreSintaticaAbstrataPrograma (asap        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarArvoreSintaticaAbstrataPrograma

  public org.omg.CORBA.Any visitarNoCadeia (br.univali.portugol.integracao.asa.NoCadeia noCadeia) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoCadeia", true);
                br.univali.portugol.integracao.asa.NoCadeiaHelper.write ($out, noCadeia);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoCadeia (noCadeia        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoCadeia

  public org.omg.CORBA.Any visitarNoCaracter (br.univali.portugol.integracao.asa.NoCaracter noCaracter) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoCaracter", true);
                br.univali.portugol.integracao.asa.NoCaracterHelper.write ($out, noCaracter);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoCaracter (noCaracter        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoCaracter

  public org.omg.CORBA.Any visitarNoCaso (br.univali.portugol.integracao.asa.NoCaso noCaso) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoCaso", true);
                br.univali.portugol.integracao.asa.NoCasoHelper.write ($out, noCaso);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoCaso (noCaso        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoCaso

  public org.omg.CORBA.Any visitarNoChamadaFuncao (br.univali.portugol.integracao.asa.NoChamadaFuncao chamadaFuncao) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoChamadaFuncao", true);
                br.univali.portugol.integracao.asa.NoChamadaFuncaoHelper.write ($out, chamadaFuncao);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoChamadaFuncao (chamadaFuncao        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoChamadaFuncao

  public org.omg.CORBA.Any visitarNoDeclaracaoFuncao (br.univali.portugol.integracao.asa.NoDeclaracaoFuncao declaracaoFuncao) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoDeclaracaoFuncao", true);
                br.univali.portugol.integracao.asa.NoDeclaracaoFuncaoHelper.write ($out, declaracaoFuncao);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoDeclaracaoFuncao (declaracaoFuncao        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoDeclaracaoFuncao

  public org.omg.CORBA.Any visitarNoDeclaracaoMatriz (br.univali.portugol.integracao.asa.NoDeclaracaoMatriz noDeclaracaoMatriz) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoDeclaracaoMatriz", true);
                br.univali.portugol.integracao.asa.NoDeclaracaoMatrizHelper.write ($out, noDeclaracaoMatriz);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoDeclaracaoMatriz (noDeclaracaoMatriz        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoDeclaracaoMatriz

  public org.omg.CORBA.Any visitarNoDeclaracaoVariavel (br.univali.portugol.integracao.asa.NoDeclaracaoVariavel noDeclaracaoVariavel) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoDeclaracaoVariavel", true);
                br.univali.portugol.integracao.asa.NoDeclaracaoVariavelHelper.write ($out, noDeclaracaoVariavel);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoDeclaracaoVariavel (noDeclaracaoVariavel        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoDeclaracaoVariavel

  public org.omg.CORBA.Any visitarNoDeclaracaoVetor (br.univali.portugol.integracao.asa.NoDeclaracaoVetor noDeclaracaoVetor) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoDeclaracaoVetor", true);
                br.univali.portugol.integracao.asa.NoDeclaracaoVetorHelper.write ($out, noDeclaracaoVetor);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoDeclaracaoVetor (noDeclaracaoVetor        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoDeclaracaoVetor

  public org.omg.CORBA.Any visitarNoDecremento (br.univali.portugol.integracao.asa.NoDecremento noDecremento) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoDecremento", true);
                br.univali.portugol.integracao.asa.NoDecrementoHelper.write ($out, noDecremento);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoDecremento (noDecremento        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoDecremento

  public org.omg.CORBA.Any visitarNoEnquanto (br.univali.portugol.integracao.asa.NoEnquanto noEnquanto) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoEnquanto", true);
                br.univali.portugol.integracao.asa.NoEnquantoHelper.write ($out, noEnquanto);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoEnquanto (noEnquanto        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoEnquanto

  public org.omg.CORBA.Any visitarNoEscolha (br.univali.portugol.integracao.asa.NoEscolha noEscolha) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoEscolha", true);
                br.univali.portugol.integracao.asa.NoEscolhaHelper.write ($out, noEscolha);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoEscolha (noEscolha        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoEscolha

  public org.omg.CORBA.Any visitarNoFacaEnquanto (br.univali.portugol.integracao.asa.NoFacaEnquanto noFacaEnquanto) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoFacaEnquanto", true);
                br.univali.portugol.integracao.asa.NoFacaEnquantoHelper.write ($out, noFacaEnquanto);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoFacaEnquanto (noFacaEnquanto        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoFacaEnquanto

  public org.omg.CORBA.Any visitarNoIncremento (br.univali.portugol.integracao.asa.NoIncremento noIncremento) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoIncremento", true);
                br.univali.portugol.integracao.asa.NoIncrementoHelper.write ($out, noIncremento);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoIncremento (noIncremento        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoIncremento

  public org.omg.CORBA.Any visitarNoInteiro (br.univali.portugol.integracao.asa.NoInteiro noInteiro) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoInteiro", true);
                br.univali.portugol.integracao.asa.NoInteiroHelper.write ($out, noInteiro);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoInteiro (noInteiro        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoInteiro

  public org.omg.CORBA.Any visitarNoLogico (br.univali.portugol.integracao.asa.NoLogico noLogico) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoLogico", true);
                br.univali.portugol.integracao.asa.NoLogicoHelper.write ($out, noLogico);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoLogico (noLogico        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoLogico

  public org.omg.CORBA.Any visitarNoMatriz (br.univali.portugol.integracao.asa.NoMatriz noMatriz) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoMatriz", true);
                br.univali.portugol.integracao.asa.NoMatrizHelper.write ($out, noMatriz);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoMatriz (noMatriz        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoMatriz

  public org.omg.CORBA.Any visitarNoMenosUnario (br.univali.portugol.integracao.asa.NoMenosUnario noMenosUnario) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoMenosUnario", true);
                br.univali.portugol.integracao.asa.NoMenosUnarioHelper.write ($out, noMenosUnario);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoMenosUnario (noMenosUnario        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoMenosUnario

  public org.omg.CORBA.Any visitarNoNao (br.univali.portugol.integracao.asa.NoNao noNao) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoNao", true);
                br.univali.portugol.integracao.asa.NoNaoHelper.write ($out, noNao);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoNao (noNao        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoNao

  public org.omg.CORBA.Any visitarNoOperacao (br.univali.portugol.integracao.asa.NoOperacao noOperacao) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoOperacao", true);
                br.univali.portugol.integracao.asa.NoOperacaoHelper.write ($out, noOperacao);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoOperacao (noOperacao        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoOperacao

  public org.omg.CORBA.Any visitarNoPara (br.univali.portugol.integracao.asa.NoPara noPara) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoPara", true);
                br.univali.portugol.integracao.asa.NoParaHelper.write ($out, noPara);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoPara (noPara        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoPara

  public org.omg.CORBA.Any visitarNoPare (br.univali.portugol.integracao.asa.NoPare noPare) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoPare", true);
                br.univali.portugol.integracao.asa.NoPareHelper.write ($out, noPare);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoPare (noPare        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoPare

  public org.omg.CORBA.Any visitarNoPercorra (br.univali.portugol.integracao.asa.NoPercorra noPercorra) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoPercorra", true);
                br.univali.portugol.integracao.asa.NoPercorraHelper.write ($out, noPercorra);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoPercorra (noPercorra        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoPercorra

  public org.omg.CORBA.Any visitarNoReal (br.univali.portugol.integracao.asa.NoReal noReal) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoReal", true);
                br.univali.portugol.integracao.asa.NoRealHelper.write ($out, noReal);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoReal (noReal        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoReal

  public org.omg.CORBA.Any visitarNoReferenciaMatriz (br.univali.portugol.integracao.asa.NoReferenciaMatriz noReferenciaMatriz) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoReferenciaMatriz", true);
                br.univali.portugol.integracao.asa.NoReferenciaMatrizHelper.write ($out, noReferenciaMatriz);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoReferenciaMatriz (noReferenciaMatriz        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoReferenciaMatriz

  public org.omg.CORBA.Any visitarNoReferenciaVariavel (br.univali.portugol.integracao.asa.NoReferenciaVariavel noReferenciaVariavel) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoReferenciaVariavel", true);
                br.univali.portugol.integracao.asa.NoReferenciaVariavelHelper.write ($out, noReferenciaVariavel);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoReferenciaVariavel (noReferenciaVariavel        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoReferenciaVariavel

  public org.omg.CORBA.Any visitarNoReferenciaVetor (br.univali.portugol.integracao.asa.NoReferenciaVetor noReferenciaVetor) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoReferenciaVetor", true);
                br.univali.portugol.integracao.asa.NoReferenciaVetorHelper.write ($out, noReferenciaVetor);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoReferenciaVetor (noReferenciaVetor        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoReferenciaVetor

  public org.omg.CORBA.Any visitarNoRetorne (br.univali.portugol.integracao.asa.NoRetorne noRetorne) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoRetorne", true);
                br.univali.portugol.integracao.asa.NoRetorneHelper.write ($out, noRetorne);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoRetorne (noRetorne        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoRetorne

  public org.omg.CORBA.Any visitarNoSe (br.univali.portugol.integracao.asa.NoSe noSe) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoSe", true);
                br.univali.portugol.integracao.asa.NoSeHelper.write ($out, noSe);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoSe (noSe        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoSe

  public org.omg.CORBA.Any visitarNoVetor (br.univali.portugol.integracao.asa.NoVetor noVetor) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoVetor", true);
                br.univali.portugol.integracao.asa.NoVetorHelper.write ($out, noVetor);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoVetor (noVetor        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoVetor

  public org.omg.CORBA.Any visitarNoDeclaracaoParametro (br.univali.portugol.integracao.asa.NoDeclaracaoParametro noDeclaracaoParametro) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("visitarNoDeclaracaoParametro", true);
                br.univali.portugol.integracao.asa.NoDeclaracaoParametroHelper.write ($out, noDeclaracaoParametro);
                $in = _invoke ($out);
                org.omg.CORBA.Any $result = $in.read_any ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:br/univali/portugol/integracao/asa/ExcecaoVisitaASA:1.0"))
                    throw br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return visitarNoDeclaracaoParametro (noDeclaracaoParametro        );
            } finally {
                _releaseReply ($in);
            }
  } // visitarNoDeclaracaoParametro

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/asa/VisitanteASA:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _VisitanteASAStub
