package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/ExcecaoVisitaASA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public final class ExcecaoVisitaASA extends org.omg.CORBA.UserException
{
  public String mensagem = null;
  public br.univali.portugol.integracao.asa.No no = null;
  public br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrata arvoreSintaticaAbstrata = null;

  public ExcecaoVisitaASA ()
  {
    super(ExcecaoVisitaASAHelper.id());
  } // ctor

  public ExcecaoVisitaASA (String _mensagem, br.univali.portugol.integracao.asa.No _no, br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrata _arvoreSintaticaAbstrata)
  {
    super(ExcecaoVisitaASAHelper.id());
    mensagem = _mensagem;
    no = _no;
    arvoreSintaticaAbstrata = _arvoreSintaticaAbstrata;
  } // ctor


  public ExcecaoVisitaASA (String $reason, String _mensagem, br.univali.portugol.integracao.asa.No _no, br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrata _arvoreSintaticaAbstrata)
  {
    super(ExcecaoVisitaASAHelper.id() + "  " + $reason);
    mensagem = _mensagem;
    no = _no;
    arvoreSintaticaAbstrata = _arvoreSintaticaAbstrata;
  } // ctor

} // class ExcecaoVisitaASA
