package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/NoBlocoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface NoBlocoOperations  extends br.univali.portugol.integracao.asa.NoOperations
{
} // interface NoBlocoOperations
