package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/NoDeclaracaoFuncaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface NoDeclaracaoFuncaoOperations  extends br.univali.portugol.integracao.asa.NoDeclaracaoOperations
{
  br.univali.portugol.integracao.asa.Quantificador getQuantificador ();
  br.univali.portugol.integracao.asa.NoBloco[] getBlocos ();
  br.univali.portugol.integracao.asa.NoDeclaracaoParametro[] getParametros ();
} // interface NoDeclaracaoFuncaoOperations
