package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/NoOperacaoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface NoOperacaoOperations  extends br.univali.portugol.integracao.asa.NoExpressaoOperations
{
  br.univali.portugol.integracao.asa.Operacao getOperacao ();
  br.univali.portugol.integracao.asa.NoExpressao getOperandoEsquerdo ();
  br.univali.portugol.integracao.asa.NoExpressao getOperandoDireito ();
  br.univali.portugol.integracao.asa.TrechoCodigoFonte getTrechoCodigoFonteOperador ();
} // interface NoOperacaoOperations
