package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/Operacao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public class Operacao implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 20;
  private static br.univali.portugol.integracao.asa.Operacao[] __array = new br.univali.portugol.integracao.asa.Operacao [__size];

  public static final int _IGUALDADE = 0;
  public static final br.univali.portugol.integracao.asa.Operacao IGUALDADE = new br.univali.portugol.integracao.asa.Operacao(_IGUALDADE);
  public static final int _DIFERENCA = 1;
  public static final br.univali.portugol.integracao.asa.Operacao DIFERENCA = new br.univali.portugol.integracao.asa.Operacao(_DIFERENCA);
  public static final int _ATRIBUICAO = 2;
  public static final br.univali.portugol.integracao.asa.Operacao ATRIBUICAO = new br.univali.portugol.integracao.asa.Operacao(_ATRIBUICAO);
  public static final int _E = 3;
  public static final br.univali.portugol.integracao.asa.Operacao E = new br.univali.portugol.integracao.asa.Operacao(_E);
  public static final int _OU = 4;
  public static final br.univali.portugol.integracao.asa.Operacao OU = new br.univali.portugol.integracao.asa.Operacao(_OU);
  public static final int _MAIOR = 5;
  public static final br.univali.portugol.integracao.asa.Operacao MAIOR = new br.univali.portugol.integracao.asa.Operacao(_MAIOR);
  public static final int _MAIOR_IGUAL = 6;
  public static final br.univali.portugol.integracao.asa.Operacao MAIOR_IGUAL = new br.univali.portugol.integracao.asa.Operacao(_MAIOR_IGUAL);
  public static final int _MENOR = 7;
  public static final br.univali.portugol.integracao.asa.Operacao MENOR = new br.univali.portugol.integracao.asa.Operacao(_MENOR);
  public static final int _MENOR_IGUAL = 8;
  public static final br.univali.portugol.integracao.asa.Operacao MENOR_IGUAL = new br.univali.portugol.integracao.asa.Operacao(_MENOR_IGUAL);
  public static final int _SOMA = 9;
  public static final br.univali.portugol.integracao.asa.Operacao SOMA = new br.univali.portugol.integracao.asa.Operacao(_SOMA);
  public static final int _SOMA_ACUMULATIVA = 10;
  public static final br.univali.portugol.integracao.asa.Operacao SOMA_ACUMULATIVA = new br.univali.portugol.integracao.asa.Operacao(_SOMA_ACUMULATIVA);
  public static final int _SUBTRACAO = 11;
  public static final br.univali.portugol.integracao.asa.Operacao SUBTRACAO = new br.univali.portugol.integracao.asa.Operacao(_SUBTRACAO);
  public static final int _SUBTRACAO_ACUMULATIVA = 12;
  public static final br.univali.portugol.integracao.asa.Operacao SUBTRACAO_ACUMULATIVA = new br.univali.portugol.integracao.asa.Operacao(_SUBTRACAO_ACUMULATIVA);
  public static final int _DIVISAO = 13;
  public static final br.univali.portugol.integracao.asa.Operacao DIVISAO = new br.univali.portugol.integracao.asa.Operacao(_DIVISAO);
  public static final int _DIVISAO_ACUMULATIVA = 14;
  public static final br.univali.portugol.integracao.asa.Operacao DIVISAO_ACUMULATIVA = new br.univali.portugol.integracao.asa.Operacao(_DIVISAO_ACUMULATIVA);
  public static final int _MULTIPLICACAO = 15;
  public static final br.univali.portugol.integracao.asa.Operacao MULTIPLICACAO = new br.univali.portugol.integracao.asa.Operacao(_MULTIPLICACAO);
  public static final int _MULTIPLICACAO_ACUMULATIVA = 16;
  public static final br.univali.portugol.integracao.asa.Operacao MULTIPLICACAO_ACUMULATIVA = new br.univali.portugol.integracao.asa.Operacao(_MULTIPLICACAO_ACUMULATIVA);
  public static final int _MODULO = 17;
  public static final br.univali.portugol.integracao.asa.Operacao MODULO = new br.univali.portugol.integracao.asa.Operacao(_MODULO);
  public static final int _MODULO_ACUMULATIVO = 18;
  public static final br.univali.portugol.integracao.asa.Operacao MODULO_ACUMULATIVO = new br.univali.portugol.integracao.asa.Operacao(_MODULO_ACUMULATIVO);
  public static final int _OPERACAO_INVALIDA = 19;
  public static final br.univali.portugol.integracao.asa.Operacao OPERACAO_INVALIDA = new br.univali.portugol.integracao.asa.Operacao(_OPERACAO_INVALIDA);

  public int value ()
  {
    return __value;
  }

  public static br.univali.portugol.integracao.asa.Operacao from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Operacao (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Operacao
