package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/TipoDado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public class TipoDado implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static br.univali.portugol.integracao.asa.TipoDado[] __array = new br.univali.portugol.integracao.asa.TipoDado [__size];

  public static final int _INTEIRO = 0;
  public static final br.univali.portugol.integracao.asa.TipoDado INTEIRO = new br.univali.portugol.integracao.asa.TipoDado(_INTEIRO);
  public static final int _REAL = 1;
  public static final br.univali.portugol.integracao.asa.TipoDado REAL = new br.univali.portugol.integracao.asa.TipoDado(_REAL);
  public static final int _LOGICO = 2;
  public static final br.univali.portugol.integracao.asa.TipoDado LOGICO = new br.univali.portugol.integracao.asa.TipoDado(_LOGICO);
  public static final int _CADEIA = 3;
  public static final br.univali.portugol.integracao.asa.TipoDado CADEIA = new br.univali.portugol.integracao.asa.TipoDado(_CADEIA);
  public static final int _CARACTER = 4;
  public static final br.univali.portugol.integracao.asa.TipoDado CARACTER = new br.univali.portugol.integracao.asa.TipoDado(_CARACTER);
  public static final int _VAZIO = 5;
  public static final br.univali.portugol.integracao.asa.TipoDado VAZIO = new br.univali.portugol.integracao.asa.TipoDado(_VAZIO);

  public int value ()
  {
    return __value;
  }

  public static br.univali.portugol.integracao.asa.TipoDado from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TipoDado (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TipoDado
