package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/ValoresMatrizHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public final class ValoresMatrizHolder implements org.omg.CORBA.portable.Streamable
{
  public org.omg.CORBA.Any value[][] = null;

  public ValoresMatrizHolder ()
  {
  }

  public ValoresMatrizHolder (org.omg.CORBA.Any[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.univali.portugol.integracao.asa.ValoresMatrizHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.univali.portugol.integracao.asa.ValoresMatrizHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.univali.portugol.integracao.asa.ValoresMatrizHelper.type ();
  }

}
