package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/VisitanteASAOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface VisitanteASAOperations 
{
  org.omg.CORBA.Any visitarArvoreSintaticaAbstrataPrograma (br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataPrograma asap) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoCadeia (br.univali.portugol.integracao.asa.NoCadeia noCadeia) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoCaracter (br.univali.portugol.integracao.asa.NoCaracter noCaracter) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoCaso (br.univali.portugol.integracao.asa.NoCaso noCaso) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoChamadaFuncao (br.univali.portugol.integracao.asa.NoChamadaFuncao chamadaFuncao) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoDeclaracaoFuncao (br.univali.portugol.integracao.asa.NoDeclaracaoFuncao declaracaoFuncao) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoDeclaracaoMatriz (br.univali.portugol.integracao.asa.NoDeclaracaoMatriz noDeclaracaoMatriz) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoDeclaracaoVariavel (br.univali.portugol.integracao.asa.NoDeclaracaoVariavel noDeclaracaoVariavel) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoDeclaracaoVetor (br.univali.portugol.integracao.asa.NoDeclaracaoVetor noDeclaracaoVetor) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoDecremento (br.univali.portugol.integracao.asa.NoDecremento noDecremento) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoEnquanto (br.univali.portugol.integracao.asa.NoEnquanto noEnquanto) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoEscolha (br.univali.portugol.integracao.asa.NoEscolha noEscolha) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoFacaEnquanto (br.univali.portugol.integracao.asa.NoFacaEnquanto noFacaEnquanto) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoIncremento (br.univali.portugol.integracao.asa.NoIncremento noIncremento) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoInteiro (br.univali.portugol.integracao.asa.NoInteiro noInteiro) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoLogico (br.univali.portugol.integracao.asa.NoLogico noLogico) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoMatriz (br.univali.portugol.integracao.asa.NoMatriz noMatriz) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoMenosUnario (br.univali.portugol.integracao.asa.NoMenosUnario noMenosUnario) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoNao (br.univali.portugol.integracao.asa.NoNao noNao) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoOperacao (br.univali.portugol.integracao.asa.NoOperacao noOperacao) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoPara (br.univali.portugol.integracao.asa.NoPara noPara) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoPare (br.univali.portugol.integracao.asa.NoPare noPare) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoPercorra (br.univali.portugol.integracao.asa.NoPercorra noPercorra) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoReal (br.univali.portugol.integracao.asa.NoReal noReal) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoReferenciaMatriz (br.univali.portugol.integracao.asa.NoReferenciaMatriz noReferenciaMatriz) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoReferenciaVariavel (br.univali.portugol.integracao.asa.NoReferenciaVariavel noReferenciaVariavel) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoReferenciaVetor (br.univali.portugol.integracao.asa.NoReferenciaVetor noReferenciaVetor) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoRetorne (br.univali.portugol.integracao.asa.NoRetorne noRetorne) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoSe (br.univali.portugol.integracao.asa.NoSe noSe) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoVetor (br.univali.portugol.integracao.asa.NoVetor noVetor) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
  org.omg.CORBA.Any visitarNoDeclaracaoParametro (br.univali.portugol.integracao.asa.NoDeclaracaoParametro noDeclaracaoParametro) throws br.univali.portugol.integracao.asa.ExcecaoVisitaASA;
} // interface VisitanteASAOperations
