package br.univali.portugol.integracao.asa;


/**
* br/univali/portugol/integracao/asa/VisitanteASAPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public abstract class VisitanteASAPOA extends org.omg.PortableServer.Servant
 implements br.univali.portugol.integracao.asa.VisitanteASAOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("visitarArvoreSintaticaAbstrataPrograma", new java.lang.Integer (0));
    _methods.put ("visitarNoCadeia", new java.lang.Integer (1));
    _methods.put ("visitarNoCaracter", new java.lang.Integer (2));
    _methods.put ("visitarNoCaso", new java.lang.Integer (3));
    _methods.put ("visitarNoChamadaFuncao", new java.lang.Integer (4));
    _methods.put ("visitarNoDeclaracaoFuncao", new java.lang.Integer (5));
    _methods.put ("visitarNoDeclaracaoMatriz", new java.lang.Integer (6));
    _methods.put ("visitarNoDeclaracaoVariavel", new java.lang.Integer (7));
    _methods.put ("visitarNoDeclaracaoVetor", new java.lang.Integer (8));
    _methods.put ("visitarNoDecremento", new java.lang.Integer (9));
    _methods.put ("visitarNoEnquanto", new java.lang.Integer (10));
    _methods.put ("visitarNoEscolha", new java.lang.Integer (11));
    _methods.put ("visitarNoFacaEnquanto", new java.lang.Integer (12));
    _methods.put ("visitarNoIncremento", new java.lang.Integer (13));
    _methods.put ("visitarNoInteiro", new java.lang.Integer (14));
    _methods.put ("visitarNoLogico", new java.lang.Integer (15));
    _methods.put ("visitarNoMatriz", new java.lang.Integer (16));
    _methods.put ("visitarNoMenosUnario", new java.lang.Integer (17));
    _methods.put ("visitarNoNao", new java.lang.Integer (18));
    _methods.put ("visitarNoOperacao", new java.lang.Integer (19));
    _methods.put ("visitarNoPara", new java.lang.Integer (20));
    _methods.put ("visitarNoPare", new java.lang.Integer (21));
    _methods.put ("visitarNoPercorra", new java.lang.Integer (22));
    _methods.put ("visitarNoReal", new java.lang.Integer (23));
    _methods.put ("visitarNoReferenciaMatriz", new java.lang.Integer (24));
    _methods.put ("visitarNoReferenciaVariavel", new java.lang.Integer (25));
    _methods.put ("visitarNoReferenciaVetor", new java.lang.Integer (26));
    _methods.put ("visitarNoRetorne", new java.lang.Integer (27));
    _methods.put ("visitarNoSe", new java.lang.Integer (28));
    _methods.put ("visitarNoVetor", new java.lang.Integer (29));
    _methods.put ("visitarNoDeclaracaoParametro", new java.lang.Integer (30));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarArvoreSintaticaAbstrataPrograma
       {
         try {
           br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataPrograma asap = br.univali.portugol.integracao.asa.ArvoreSintaticaAbstrataProgramaHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarArvoreSintaticaAbstrataPrograma (asap);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoCadeia
       {
         try {
           br.univali.portugol.integracao.asa.NoCadeia noCadeia = br.univali.portugol.integracao.asa.NoCadeiaHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoCadeia (noCadeia);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoCaracter
       {
         try {
           br.univali.portugol.integracao.asa.NoCaracter noCaracter = br.univali.portugol.integracao.asa.NoCaracterHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoCaracter (noCaracter);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoCaso
       {
         try {
           br.univali.portugol.integracao.asa.NoCaso noCaso = br.univali.portugol.integracao.asa.NoCasoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoCaso (noCaso);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 4:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoChamadaFuncao
       {
         try {
           br.univali.portugol.integracao.asa.NoChamadaFuncao chamadaFuncao = br.univali.portugol.integracao.asa.NoChamadaFuncaoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoChamadaFuncao (chamadaFuncao);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoDeclaracaoFuncao
       {
         try {
           br.univali.portugol.integracao.asa.NoDeclaracaoFuncao declaracaoFuncao = br.univali.portugol.integracao.asa.NoDeclaracaoFuncaoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoDeclaracaoFuncao (declaracaoFuncao);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 6:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoDeclaracaoMatriz
       {
         try {
           br.univali.portugol.integracao.asa.NoDeclaracaoMatriz noDeclaracaoMatriz = br.univali.portugol.integracao.asa.NoDeclaracaoMatrizHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoDeclaracaoMatriz (noDeclaracaoMatriz);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 7:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoDeclaracaoVariavel
       {
         try {
           br.univali.portugol.integracao.asa.NoDeclaracaoVariavel noDeclaracaoVariavel = br.univali.portugol.integracao.asa.NoDeclaracaoVariavelHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoDeclaracaoVariavel (noDeclaracaoVariavel);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 8:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoDeclaracaoVetor
       {
         try {
           br.univali.portugol.integracao.asa.NoDeclaracaoVetor noDeclaracaoVetor = br.univali.portugol.integracao.asa.NoDeclaracaoVetorHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoDeclaracaoVetor (noDeclaracaoVetor);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 9:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoDecremento
       {
         try {
           br.univali.portugol.integracao.asa.NoDecremento noDecremento = br.univali.portugol.integracao.asa.NoDecrementoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoDecremento (noDecremento);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 10:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoEnquanto
       {
         try {
           br.univali.portugol.integracao.asa.NoEnquanto noEnquanto = br.univali.portugol.integracao.asa.NoEnquantoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoEnquanto (noEnquanto);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 11:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoEscolha
       {
         try {
           br.univali.portugol.integracao.asa.NoEscolha noEscolha = br.univali.portugol.integracao.asa.NoEscolhaHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoEscolha (noEscolha);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 12:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoFacaEnquanto
       {
         try {
           br.univali.portugol.integracao.asa.NoFacaEnquanto noFacaEnquanto = br.univali.portugol.integracao.asa.NoFacaEnquantoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoFacaEnquanto (noFacaEnquanto);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 13:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoIncremento
       {
         try {
           br.univali.portugol.integracao.asa.NoIncremento noIncremento = br.univali.portugol.integracao.asa.NoIncrementoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoIncremento (noIncremento);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 14:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoInteiro
       {
         try {
           br.univali.portugol.integracao.asa.NoInteiro noInteiro = br.univali.portugol.integracao.asa.NoInteiroHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoInteiro (noInteiro);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 15:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoLogico
       {
         try {
           br.univali.portugol.integracao.asa.NoLogico noLogico = br.univali.portugol.integracao.asa.NoLogicoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoLogico (noLogico);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 16:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoMatriz
       {
         try {
           br.univali.portugol.integracao.asa.NoMatriz noMatriz = br.univali.portugol.integracao.asa.NoMatrizHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoMatriz (noMatriz);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 17:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoMenosUnario
       {
         try {
           br.univali.portugol.integracao.asa.NoMenosUnario noMenosUnario = br.univali.portugol.integracao.asa.NoMenosUnarioHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoMenosUnario (noMenosUnario);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 18:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoNao
       {
         try {
           br.univali.portugol.integracao.asa.NoNao noNao = br.univali.portugol.integracao.asa.NoNaoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoNao (noNao);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 19:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoOperacao
       {
         try {
           br.univali.portugol.integracao.asa.NoOperacao noOperacao = br.univali.portugol.integracao.asa.NoOperacaoHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoOperacao (noOperacao);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 20:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoPara
       {
         try {
           br.univali.portugol.integracao.asa.NoPara noPara = br.univali.portugol.integracao.asa.NoParaHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoPara (noPara);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 21:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoPare
       {
         try {
           br.univali.portugol.integracao.asa.NoPare noPare = br.univali.portugol.integracao.asa.NoPareHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoPare (noPare);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 22:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoPercorra
       {
         try {
           br.univali.portugol.integracao.asa.NoPercorra noPercorra = br.univali.portugol.integracao.asa.NoPercorraHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoPercorra (noPercorra);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 23:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoReal
       {
         try {
           br.univali.portugol.integracao.asa.NoReal noReal = br.univali.portugol.integracao.asa.NoRealHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoReal (noReal);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 24:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoReferenciaMatriz
       {
         try {
           br.univali.portugol.integracao.asa.NoReferenciaMatriz noReferenciaMatriz = br.univali.portugol.integracao.asa.NoReferenciaMatrizHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoReferenciaMatriz (noReferenciaMatriz);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 25:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoReferenciaVariavel
       {
         try {
           br.univali.portugol.integracao.asa.NoReferenciaVariavel noReferenciaVariavel = br.univali.portugol.integracao.asa.NoReferenciaVariavelHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoReferenciaVariavel (noReferenciaVariavel);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 26:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoReferenciaVetor
       {
         try {
           br.univali.portugol.integracao.asa.NoReferenciaVetor noReferenciaVetor = br.univali.portugol.integracao.asa.NoReferenciaVetorHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoReferenciaVetor (noReferenciaVetor);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 27:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoRetorne
       {
         try {
           br.univali.portugol.integracao.asa.NoRetorne noRetorne = br.univali.portugol.integracao.asa.NoRetorneHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoRetorne (noRetorne);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 28:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoSe
       {
         try {
           br.univali.portugol.integracao.asa.NoSe noSe = br.univali.portugol.integracao.asa.NoSeHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoSe (noSe);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 29:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoVetor
       {
         try {
           br.univali.portugol.integracao.asa.NoVetor noVetor = br.univali.portugol.integracao.asa.NoVetorHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoVetor (noVetor);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       case 30:  // br/univali/portugol/integracao/asa/VisitanteASA/visitarNoDeclaracaoParametro
       {
         try {
           br.univali.portugol.integracao.asa.NoDeclaracaoParametro noDeclaracaoParametro = br.univali.portugol.integracao.asa.NoDeclaracaoParametroHelper.read (in);
           org.omg.CORBA.Any $result = null;
           $result = this.visitarNoDeclaracaoParametro (noDeclaracaoParametro);
           out = $rh.createReply();
           out.write_any ($result);
         } catch (br.univali.portugol.integracao.asa.ExcecaoVisitaASA $ex) {
           out = $rh.createExceptionReply ();
           br.univali.portugol.integracao.asa.ExcecaoVisitaASAHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/asa/VisitanteASA:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public VisitanteASA _this() 
  {
    return VisitanteASAHelper.narrow(
    super._this_object());
  }

  public VisitanteASA _this(org.omg.CORBA.ORB orb) 
  {
    return VisitanteASAHelper.narrow(
    super._this_object(orb));
  }


} // class VisitanteASAPOA
