package br.univali.portugol.integracao.mensagens;


/**
* br/univali/portugol/integracao/mensagens/ErroSemantico.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public final class ErroSemantico extends org.omg.CORBA.UserException
{
  public String mensagem = null;
  public int linha = (int)0;
  public int coluna = (int)0;

  public ErroSemantico ()
  {
    super(ErroSemanticoHelper.id());
  } // ctor

  public ErroSemantico (String _mensagem, int _linha, int _coluna)
  {
    super(ErroSemanticoHelper.id());
    mensagem = _mensagem;
    linha = _linha;
    coluna = _coluna;
  } // ctor


  public ErroSemantico (String $reason, String _mensagem, int _linha, int _coluna)
  {
    super(ErroSemanticoHelper.id() + "  " + $reason);
    mensagem = _mensagem;
    linha = _linha;
    coluna = _coluna;
  } // ctor

} // class ErroSemantico
