package br.univali.portugol.integracao.mensagens;

/**
* br/univali/portugol/integracao/mensagens/ErroSintaticoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public final class ErroSintaticoHolder implements org.omg.CORBA.portable.Streamable
{
  public br.univali.portugol.integracao.mensagens.ErroSintatico value = null;

  public ErroSintaticoHolder ()
  {
  }

  public ErroSintaticoHolder (br.univali.portugol.integracao.mensagens.ErroSintatico initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.univali.portugol.integracao.mensagens.ErroSintaticoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.univali.portugol.integracao.mensagens.ErroSintaticoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.univali.portugol.integracao.mensagens.ErroSintaticoHelper.type ();
  }

}
