package br.univali.portugol.integracao.mensagens;


/**
* br/univali/portugol/integracao/mensagens/ErroExecucao.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public final class ErroExecucao extends org.omg.CORBA.UserException
{
  public String mensagem = null;

  public ErroExecucao ()
  {
    super(ErroExecucaoHelper.id());
  } // ctor

  public ErroExecucao (String _mensagem)
  {
    super(ErroExecucaoHelper.id());
    mensagem = _mensagem;
  } // ctor


  public ErroExecucao (String $reason, String _mensagem)
  {
    super(ErroExecucaoHelper.id() + "  " + $reason);
    mensagem = _mensagem;
  } // ctor

} // class ErroExecucao
