package br.univali.portugol.integracao.mensagens;


/**
* br/univali/portugol/integracao/mensagens/ErroExecucaoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

abstract public class ErroExecucaoHelper
{
  private static String  _id = "IDL:br/univali/portugol/integracao/mensagens/ErroExecucao:1.0";

  public static void insert (org.omg.CORBA.Any a, br.univali.portugol.integracao.mensagens.ErroExecucao that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.univali.portugol.integracao.mensagens.ErroExecucao extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "mensagem",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (br.univali.portugol.integracao.mensagens.ErroExecucaoHelper.id (), "ErroExecucao", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.univali.portugol.integracao.mensagens.ErroExecucao read (org.omg.CORBA.portable.InputStream istream)
  {
    br.univali.portugol.integracao.mensagens.ErroExecucao value = new br.univali.portugol.integracao.mensagens.ErroExecucao ();
    // read and discard the repository ID
    istream.read_string ();
    value.mensagem = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.univali.portugol.integracao.mensagens.ErroExecucao value)
  {
    // write the repository ID
    ostream.write_string (id ());
    ostream.write_string (value.mensagem);
  }

}
