package br.univali.portugol.integracao.execucao;


/**
* br/univali/portugol/integracao/execucao/ModoEncerramento.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public class ModoEncerramento implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static br.univali.portugol.integracao.execucao.ModoEncerramento[] __array = new br.univali.portugol.integracao.execucao.ModoEncerramento [__size];

  public static final int _NORMAL = 0;
  public static final br.univali.portugol.integracao.execucao.ModoEncerramento NORMAL = new br.univali.portugol.integracao.execucao.ModoEncerramento(_NORMAL);
  public static final int _ERRO = 1;
  public static final br.univali.portugol.integracao.execucao.ModoEncerramento ERRO = new br.univali.portugol.integracao.execucao.ModoEncerramento(_ERRO);
  public static final int _INTERRUPCAO = 2;
  public static final br.univali.portugol.integracao.execucao.ModoEncerramento INTERRUPCAO = new br.univali.portugol.integracao.execucao.ModoEncerramento(_INTERRUPCAO);

  public int value ()
  {
    return __value;
  }

  public static br.univali.portugol.integracao.execucao.ModoEncerramento from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ModoEncerramento (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ModoEncerramento
