package br.univali.portugol.integracao.execucao;

/**
* br/univali/portugol/integracao/execucao/ObservadorExecucaoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public final class ObservadorExecucaoHolder implements org.omg.CORBA.portable.Streamable
{
  public br.univali.portugol.integracao.execucao.ObservadorExecucao value = null;

  public ObservadorExecucaoHolder ()
  {
  }

  public ObservadorExecucaoHolder (br.univali.portugol.integracao.execucao.ObservadorExecucao initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.univali.portugol.integracao.execucao.ObservadorExecucaoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.univali.portugol.integracao.execucao.ObservadorExecucaoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.univali.portugol.integracao.execucao.ObservadorExecucaoHelper.type ();
  }

}
