package br.univali.portugol.integracao.execucao;


/**
* br/univali/portugol/integracao/execucao/SaidaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface SaidaOperations 
{
  void limpar () throws br.univali.portugol.integracao.Excecao;
  void escreverCadeia (String valor) throws br.univali.portugol.integracao.Excecao;
  void escreverLogico (boolean valor) throws br.univali.portugol.integracao.Excecao;
  void escreverInteiro (int valor) throws br.univali.portugol.integracao.Excecao;
  void escreverReal (double valor) throws br.univali.portugol.integracao.Excecao;
  void escreverCaracter (char valor) throws br.univali.portugol.integracao.Excecao;
} // interface SaidaOperations
