package br.univali.portugol.integracao.analise;


/**
* br/univali/portugol/integracao/analise/ListaAvisoAnaliseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/

public final class ListaAvisoAnaliseHolder implements org.omg.CORBA.portable.Streamable
{
  public br.univali.portugol.integracao.mensagens.AvisoAnalise value[] = null;

  public ListaAvisoAnaliseHolder ()
  {
  }

  public ListaAvisoAnaliseHolder (br.univali.portugol.integracao.mensagens.AvisoAnalise[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.univali.portugol.integracao.analise.ListaAvisoAnaliseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.univali.portugol.integracao.analise.ListaAvisoAnaliseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.univali.portugol.integracao.analise.ListaAvisoAnaliseHelper.type ();
  }

}
