package br.univali.portugol.integracao.analise;


/**
* br/univali/portugol/integracao/analise/ResultadoAnaliseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public interface ResultadoAnaliseOperations 
{
  int getNumeroTotalErros ();
  int getNumeroErrosSintaticos ();
  int getNumeroErrosSemanticos ();
  int getNumeroAvisos ();
  br.univali.portugol.integracao.mensagens.AvisoAnalise[] getAvisos ();
  br.univali.portugol.integracao.mensagens.ErroSintatico[] getErrosSintaticos ();
  br.univali.portugol.integracao.mensagens.ErroSemantico[] getErrosSemanticos ();
} // interface ResultadoAnaliseOperations
