package br.univali.portugol.integracao.analise;


/**
* br/univali/portugol/integracao/analise/ResultadoAnalisePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/Luiz Fernando/Documentos/Projetos/Portugol_X/Codigo-Fonte/Portugol-Integracao/src/br/univali/portugol/integracao/Portugol.idl
* Quarta-feira, 2 de Maio de 2012 07h25min01s BRT
*/


//==========================================================================================//
public abstract class ResultadoAnalisePOA extends org.omg.PortableServer.Servant
 implements br.univali.portugol.integracao.analise.ResultadoAnaliseOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getNumeroTotalErros", new java.lang.Integer (0));
    _methods.put ("getNumeroErrosSintaticos", new java.lang.Integer (1));
    _methods.put ("getNumeroErrosSemanticos", new java.lang.Integer (2));
    _methods.put ("getNumeroAvisos", new java.lang.Integer (3));
    _methods.put ("getAvisos", new java.lang.Integer (4));
    _methods.put ("getErrosSintaticos", new java.lang.Integer (5));
    _methods.put ("getErrosSemanticos", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/univali/portugol/integracao/analise/ResultadoAnalise/getNumeroTotalErros
       {
         int $result = (int)0;
         $result = this.getNumeroTotalErros ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // br/univali/portugol/integracao/analise/ResultadoAnalise/getNumeroErrosSintaticos
       {
         int $result = (int)0;
         $result = this.getNumeroErrosSintaticos ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // br/univali/portugol/integracao/analise/ResultadoAnalise/getNumeroErrosSemanticos
       {
         int $result = (int)0;
         $result = this.getNumeroErrosSemanticos ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // br/univali/portugol/integracao/analise/ResultadoAnalise/getNumeroAvisos
       {
         int $result = (int)0;
         $result = this.getNumeroAvisos ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // br/univali/portugol/integracao/analise/ResultadoAnalise/getAvisos
       {
         br.univali.portugol.integracao.mensagens.AvisoAnalise $result[] = null;
         $result = this.getAvisos ();
         out = $rh.createReply();
         br.univali.portugol.integracao.analise.ListaAvisoAnaliseHelper.write (out, $result);
         break;
       }

       case 5:  // br/univali/portugol/integracao/analise/ResultadoAnalise/getErrosSintaticos
       {
         br.univali.portugol.integracao.mensagens.ErroSintatico $result[] = null;
         $result = this.getErrosSintaticos ();
         out = $rh.createReply();
         br.univali.portugol.integracao.analise.ListaErroSintaticoHelper.write (out, $result);
         break;
       }

       case 6:  // br/univali/portugol/integracao/analise/ResultadoAnalise/getErrosSemanticos
       {
         br.univali.portugol.integracao.mensagens.ErroSemantico $result[] = null;
         $result = this.getErrosSemanticos ();
         out = $rh.createReply();
         br.univali.portugol.integracao.analise.ListaErroSemanticoHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/univali/portugol/integracao/analise/ResultadoAnalise:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ResultadoAnalise _this() 
  {
    return ResultadoAnaliseHelper.narrow(
    super._this_object());
  }

  public ResultadoAnalise _this(org.omg.CORBA.ORB orb) 
  {
    return ResultadoAnaliseHelper.narrow(
    super._this_object(orb));
  }


} // class ResultadoAnalisePOA
